### ISSUE TITLE
Use of (unsigned long long) in _log2 macro?

### ISSUE THREAD

**Issue by matlabuser77** [nqtronix/fifofast#3]
In macro_math.h, line 48 causes a number of compiler warnings in my project:
```#define _log2(n)	((unsigned) (8*sizeof (unsigned long long) - __builtin_clzll((n)) - 1))```

The compiler warnings received are:
```ISO C90 does not support 'long long' [-Wlong-long]```

Replacing the (unsigned long long) with the (uint64_t) type fixes the compiler warnings in my project:
```#define _log2(n)	((unsigned) (8*sizeof (uint64_t) - __builtin_clzll((n)) - 1))```

Note that the following flag is set (by default in my Atmel Studio project--I haven't changed it...) in the "Miscellaneous" section of ARM/GNU C Compiler flags:
```-std=gnu99```

Is my substitution of (uint64_t) for (unsigned long long) a valid change? Thanks!

**Comment by nqtronix** [comment]
Unlike you I don't get any warnings and the code is intended to be C99 anyway.

Your change is valid because `uint64_t` is the same size as `unsigned long long`. I prefer it also as it is more descriptive. I'll push the fix in the next commit. Thanks.
